---
title: "Reading note: Difference-in-differences with a continuous treatment"
author: "Ming Yuan"
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: true
editor: visual
---

> [Callaway, Brantly, Andrew Goodman-Bacon, and Pedro HC Sant'Anna. "Difference-in-Differences with a Continuous Treatment." arXiv." *Preprint posted online July* 9 (2021).](https://arxiv.org/abs/2107.02637)

## Keywords

Difference-in-differences; Continuous treatment; Multi-valued discrete treatment; Parallel trends; Two-way fixed effects; Multiple periods; Variation in treatment timing; Treatment effect heterogeneity.

> Difference-in-difference (DID) is a quasi-experimental design that makes use of longitudinal data from treatment and control groups to obtain an appropriate counterfactual to estimate a causal effect.\
> - <https://en.wikipedia.org/wiki/Difference_in_differences>;\
> - <https://www.publichealth.columbia.edu/research/population-health-methods/difference-difference-estimation>

## Abstract

This paper analyzes **difference-in-differences** designs with a continuous treatment.

We show that **treatment effect on the treated-type parameters can be identified under a generalized parallel trends assumption that is similar to the binary treatment setup**.

However, **interpreting differences in these parameters** across different values of the treatment can be particularly challenging due to **selection bias** that is not ruled out by the parallel trends assumption. We discuss alternative, typically stronger, assumptions that alleviate these challenges.

We also provide a variety of treatment effect decomposition results, highlighting that parameters associated with popular **linear two-way fixed-effect (TWFE)** specifications can be hard to interpret, even when there are only two time periods.

We introduce alternative estimation procedures that do not suffer from these TWFE drawbacks, and show in an application that they can lead to different conclusions.
